# Generated by Django 3.1.5 on 2021-01-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_cbo', models.CharField(max_length=150)),
                ('nome_radio_comunitaria', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('ret_geral_spots', models.IntegerField()),
                ('ret_geral_debates', models.IntegerField()),
                ('ret_geral_obs', models.IntegerField()),
                ('ret_gravida_spots', models.IntegerField()),
                ('ret_gravida_debates', models.IntegerField()),
                ('ret_gravida_obs', models.IntegerField()),
                ('tb_hiv_spots', models.IntegerField()),
                ('tb_hiv_debates', models.IntegerField()),
                ('tb_hiv_obs', models.IntegerField()),
                ('tarv_crianca_spots', models.IntegerField()),
                ('tarv_crianca_debates', models.IntegerField()),
                ('tarv_crianca_obs', models.IntegerField()),
                ('gbv_spots', models.IntegerField()),
                ('gbv_debates', models.IntegerField()),
                ('literacia_tarv_spot', models.IntegerField()),
                ('literacia_tarv_database', models.IntegerField()),
                ('literacia_tarv_obs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSanitaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='ResumoMensalVSL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa_facilitador', models.CharField(max_length=150)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('total_grupos', models.IntegerField()),
                ('num_novos_mes', models.IntegerField()),
                ('num_grupos_encerram_ciclo', models.IntegerField()),
                ('membros_feminino', models.IntegerField()),
                ('membros_masculino', models.IntegerField()),
                ('membros_feminino_HIV_Pos', models.IntegerField()),
                ('membros_masculino_HIV_Pos', models.IntegerField()),
                ('perc_membros_feminino_HIV_Pos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perc_membros_masculino_HIV_Pos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuid_cov_feminino', models.IntegerField()),
                ('cuid_cov_masculino', models.IntegerField()),
                ('membros_gaac_feminino', models.IntegerField()),
                ('membros_gaac_masculino', models.IntegerField()),
                ('outros_membros_feminino', models.IntegerField()),
                ('outros_membros_masculino', models.IntegerField()),
                ('membros_cs_feminino', models.IntegerField()),
                ('membros_cs_masculino', models.IntegerField()),
                ('membros_maes_feminino', models.IntegerField()),
                ('membros_maes_masculino', models.IntegerField()),
                ('unidade_sanitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesanitaria')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
        migrations.CreateModel(
            name='DialogoComunitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_facilitador', models.CharField(max_length=150)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('total_grupos', models.IntegerField()),
                ('grupos_novos_mes', models.IntegerField()),
                ('grupos_encerram_ciclo', models.IntegerField()),
                ('participantes_fem_20_24', models.IntegerField()),
                ('participantes_fem_25_plus', models.IntegerField()),
                ('participantes_fem_15_19', models.IntegerField()),
                ('participantes_masc_20_24', models.IntegerField()),
                ('participantes_masc_25_plus', models.IntegerField()),
                ('participantes_masc_15_19', models.IntegerField()),
                ('referido', models.IntegerField()),
                ('testagem', models.IntegerField()),
                ('outros_servicos', models.IntegerField()),
                ('unidade_sanitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesanitaria')),
            ],
        ),
        migrations.CreateModel(
            name='ActaMensalCG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encontro', models.DateField()),
                ('data_proximo_encontro', models.DateField()),
                ('num_homens', models.IntegerField()),
                ('num_mulheres', models.IntegerField()),
                ('nome_pessoa_facilitador', models.CharField(max_length=150)),
                ('unidade_sanitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadesanitaria')),
            ],
        ),
    ]
