# Generated by Django 3.1.5 on 2021-01-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaMensalCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encontro', models.DateField()),
                ('data_proximo_encontro', models.DateField()),
                ('participantes_homens', models.IntegerField()),
                ('participantes_mulheres', models.IntegerField()),
                ('nome_facilitador', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='actamensalcg',
            old_name='nome_pessoa_facilitador',
            new_name='nome_facilitador',
        ),
        migrations.RenameField(
            model_name='actamensalcg',
            old_name='num_homens',
            new_name='nparticipantes_homens',
        ),
        migrations.RenameField(
            model_name='actamensalcg',
            old_name='num_mulheres',
            new_name='participantes_mulheres',
        ),
    ]
