# Generated by Django 3.1.5 on 2021-01-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actamensalcs_unidade_sanitaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actamensalcs',
            name='data_encontro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actamensalcs',
            name='data_proximo_encontro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actamensalcs',
            name='nome_facilitador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='actamensalcs',
            name='participantes_homens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actamensalcs',
            name='participantes_mulheres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
