# Generated by Django 3.1.5 on 2021-01-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210125_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actamensalcg',
            old_name='nparticipantes_homens',
            new_name='participantes_homens',
        ),
    ]
